name: banthu_app
description: "Banthu is a leading B2B Marketplace in Thailand that bridges the gap between local businesses and top-tier Chinese suppliers"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  go_router: ^15.2.0
  unicons: ^3.0.0
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  equatable: ^2.0.7
  toastification: ^3.0.3
  rxdart: ^0.28.0
  sliver_expandable: ^1.1.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  pretty_dio_logger: ^1.4.0
  jwt_decoder: ^2.0.1
  get_it: ^8.0.3
  flutter_udid: ^4.0.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  # floating_draggable_widget: ^2.3.0
  scrollable_positioned_list: ^0.3.8
  get_video_thumbnail: ^0.7.0
  chewie: ^1.12.1
  video_player: ^2.10.0
  shimmer: ^3.0.0
  easy_localization: ^3.0.7+1
  wolt_modal_sheet: ^0.11.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.2.0

flutter:
  default-flavor: development
  uses-material-design: true
  assets:
    - assets/images/background_banner_request_product.png
    - assets/icons/ic_banthu_navbar.svg
    - assets/icons/ic_quotation_navbar.svg
    - assets/images/product_request_illustration.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/sample_img.jpg
    - assets/images/ic_1688.png
    - assets/images/GigaFactoryBadge.png
    - assets/images/ic_cogs.png
    - assets/icons/ic_about_banthu.png
    - assets/icons/ic_banthu_wallet.png
    - assets/icons/ic_howtoorder.png
    - assets/icons/ic_product_tips.png
    - assets/icons/ic_tnc.png
    - assets/icons/Price All-in.png
    - assets/icons/Free Membership.png
    - assets/icons/Free Shipping.png
    - assets/icons/Payment Secure.png
    - assets/icons/Taobao_Logo.png
    - assets/icons/Alibaba-logo.png
    - assets/icons/taurus.png
    - assets/images/no_product_ilustration.png
    - assets/icons/default_category_image.png
    - assets/icons/recommended.png
    - assets/icons/ic_to_receive.png
    - assets/icons/ic_adjust_bill.png
    - assets/icons/ic_quotation_process.png
    - assets/icons/ic_shipping.png
    - assets/icons/ic_to_pay.png
    - assets/images/sign_out_illustration.png
    - assets/images/E-Commerce 02.png
    - assets/translations/en-TH.json
    - assets/translations/th-TH.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
